const menus = [
  {
    shop: '김치찌개',
    name: '전통숙성 황실김치찜&찌개 고양점',
    mainMenu: '한그릇 [숙성삼겹] 황실김치찌개',
    img: 'images/kimchi.jpg',
    price: '13,900원',
  },
  {
    shop: '햄버거',
    name: '맥도날드 고양DT점',
    mainMenu: '맥스파이시 상하이버거 세트',
    img: 'images/burger.jpg',
    price: '9,100원',
  },
  {
    shop: '짜장면',
    name: '차이나하오치',
    mainMenu: '짜장면',
    img: 'images/jjajang.jpg',
    price: '7,000원',
  },
  {
    shop: '짬뽕',
    name: '차이나하오치',
    mainMenu: '차돌왕짬뽕',
    img: 'images/jjamppong.jpg',
    price: '12,000원',
  },
  {
    shop: '김밥',
    name: '김가네 벽제점',
    mainMenu: '김가네김밥',
    img: 'images/kimbap.jpg',
    price: '4,500원',
  },
  {
    shop: '마라탕',
    name: '황비홍마라탕 고양점',
    mainMenu: '내맘대로 마라탕',
    img: 'images/malatang.jpg',
    price: '13,500원',
  },
  {
    shop: '치킨',
    name: 'BBQ 고양고골길점',
    mainMenu: '황금올리브치킨',
    img: 'images/chicken.jpg',
    price: '25,000원',
  },
  {
    shop: '초밥',
    name: '육회왕자 연어공주 고양동점',
    mainMenu: '모듬초밥',
    img: 'images/sushi.jpg',
    price: '15,900원',
  },
  {
    shop: '떡볶이',
    name: '배떡 고양동점',
    mainMenu: '로제 떡볶이',
    img: 'images/tteokbokki.jpg',
    price: '11,000원',
  },
  {
    shop: '국밥',
    name: '손큰할매순대국',
    mainMenu: '순대국',
    img: 'images/gukbap.jpg',
    price: '10,000원',
  },
  {
    shop: '도시락',
    name: '한솥도시락 고양푸른마을점',
    mainMenu: '치킨마요',
    img: 'images/dosirak.jpg',
    price: '4,700원',
  },
  {
    shop: '찜닭',
    name: '동궁 찜닭 고양점',
    mainMenu: '동궁 황금찜닭',
    img: 'images/jjimdak.jpg',
    price: '23,000원',
  },
  {
    shop: '돈가스',
    name: '미소야 고양동점',
    mainMenu: '로스카츠',
    img: 'images/donkatsu.jpg',
    price: '11,000원',
  },
  {
    shop: '죽',
    name: '본죽 고양점',
    mainMenu: '전복죽',
    img: 'images/juk.jpg',
    price: '14,000원',
  },
  {
    shop: '쌀국수',
    name: '누들홀릭쌀국수',
    mainMenu: '차돌양지쌀국수',
    img: 'images/pho.jpg',
    price: '9,000원',
  },
  {
    shop: '보쌈',
    name: '성수보쌈 대자본점',
    mainMenu: '보쌈정식 도시락',
    img: 'images/bossam.jpg',
    price: '13,000원',
  },
  {
    shop: '파스타',
    name: '파스타일 파스타&필라프 고양동점',
    mainMenu: '까르보나라 파스타',
    img: 'images/pasta.jpg',
    price: '11,900원',
  },
  {
    shop: '삼겹살',
    name: '쫄면주는삼겹본능by놀부 고양점',
    mainMenu: '구이삼겹',
    img: 'images/samgyeopsal.jpg',
    price: '17,900원',
  },
  {
    shop: '덮밥',
    name: '핵밥 고양관산점',
    mainMenu: '연어덮밥',
    img: 'images/donburi.jpg',
    price: '15,900원',
  },
  {
    shop: '냉면',
    name: '인생 냉면 고양동점',
    mainMenu: '물 비빔냉면',
    img: 'images/naengmyeon.jpg',
    price: '10,900원',
  },
  {
    shop: '밥버거',
    name: '봉구스밥버거 고양동점',
    mainMenu: '햄치즈 밥버거',
    img: 'images/bapburger.jpg',
    price: '5,100원',
  },
  {
    shop: '닭볶음탕',
    name: '계근상 고양점',
    mainMenu: '1인 순살 닭도리탕',
    img: 'images/dakbokkeumtang.jpg',
    price: '13,000원',
  },
  {
    shop: '곱창',
    name: '동대문곱창',
    mainMenu: '야채곱창 2인분',
    img: 'images/gopchang.jpg',
    price: '26,000원',
  },
  {
    shop: '제육볶음',
    name: '고기듬뿍 국물두루치기&밥도둑 짜글이 덕양점',
    mainMenu: '고기듬뿍두루치기',
    img: 'images/jeyuk.jpg',
    price: '15,900원',
  },
  {
    shop: '샐러드',
    name: '샐러드킹 다이어트 고양동점',
    mainMenu: '부채살 스테이크 샐러드플래터',
    img: 'images/salad.jpg',
    price: '15,900원',
  },
  {
    shop: '닭발',
    name: '닭발공작소 고양덕양점',
    mainMenu: '직화무뼈닭발',
    img: 'images/dakbal.jpg',
    price: '20,000원',
  },
  {
    shop: '칼국수',
    name: '소담',
    mainMenu: '바지락칼국수',
    img: 'images/kalguksu.jpg',
    price: '10,000원',
  },
  {
    shop: '피자',
    name: '자가제빵 선명희피자 고양점',
    mainMenu: '내 맘대로 반반~한 피자',
    img: 'images/pizza.jpg',
    price: '21,000원',
  },
  {
    shop: '카레',
    name: '카레세끼 매운숙성카페전문 고양덕양점',
    mainMenu: '돈까스 에그스크램블 카레',
    img: 'images/curry.jpg',
    price: '14,900원',
  },
  {
    shop: '토스트',
    name: '토스트굽는사람들',
    mainMenu: '햄치즈토스트',
    img: 'images/toast.jpg',
    price: '4,100원',
  },
  {
    shop: '부대찌개',
    name: '땅스부대찌개 고양점',
    mainMenu: '오리지널 부대찌개 3인분',
    img: 'images/budae.jpg',
    price: '16,900원',
  },
  {
    shop: '오므라이스',
    name: '오늘은 오므라이스 고양점',
    mainMenu: '대왕소세지 오므라이스',
    img: 'images/omurice.jpg',
    price: '15,000원',
  },
  {
    shop: '한식뷔페',
    name: '골목길식당(중부대학교 입구)',
    mainMenu: '1인',
    img: 'images/hansikbuffet.jpg',
    price: '8,800원',
  },
  {
    shop: '국수',
    name: '울엄마 맛국수(중부대학교 입구)',
    mainMenu: '비빔국수',
    img: 'images/guksu.jpg',
    price: '5,000원',
  },
  {
    shop: '학식',
    name: '중부대학교 식당',
    mainMenu: '한식, 돈가스',
    img: 'images/haksik.jpg',
    price: '6,000원~7,500원',
  },
  {
    shop: '브런치',
    name: '빅브레드 고양점',
    mainMenu: '빅사이즈 고기고기 파이+빵반찬 120G',
    img: 'images/brunch.jpg',
    price: '7,800원',
  },
  {
    shop: '간장게장',
    name: '신밥도둑꽃게장 고양점',
    mainMenu: '꽃게1인 간장게장 정식 도시락',
    img: 'images/ganjanggejang.jpg',
    price: '19,500원',
  },
  {
    shop: '볶음밥',
    name: '밥앤동 볶음밥&우동 고양점',
    mainMenu: '삼겹 김치볶음밥',
    img: 'images/bokkeumbap.jpg',
    price: '11,900원',
  },
  {
    shop: '족발',
    name: '성수보쌈 대자본점',
    mainMenu: '족발정식 도시락',
    img: 'images/jokbal.jpg',
    price: '13,000원',
  },
  {
    shop: '콩나물불고기',
    name: '밥꼬콩불 고양내유점',
    mainMenu: '1인 매콤 콩불콩불',
    img: 'images/kongbul.jpg',
    price: '17,000원',
  },
  {
    shop: '만두',
    name: '미호만두',
    mainMenu: '김치만두, 고기만두',
    img: 'images/mandu.jpg',
    price: '6,500원',
  },
  {
    shop: '꼬치',
    name: '꼬치의품격 고양푸른마을점',
    mainMenu: '소금 구이 닭꼬치',
    img: 'images/kkkochi.jpg',
    price: '4,500원',
  },
  {
    shop: '쭈꾸미',
    name: '불났쭈 양념쭈꾸미&갑오징어 고양점',
    mainMenu: '1인 직화 쭈꾸미 세트',
    img: 'images/jjukkumi.jpg',
    price: '18,900원',
  },
  {
    shop: '회덮밥',
    name: '울돌목횟집',
    mainMenu: '회덮밥',
    img: 'images/hoedupbap.jpg',
    price: '13,000원',
  },
  {
    shop: '고등어조림',
    name: '명가잔치상',
    mainMenu: '고등어조림',
    img: 'images/godeungeo.jpg',
    price: '14,000원',
  },
  {
    shop: '갈비탕',
    name: '한우존',
    mainMenu: '왕갈비탕',
    img: 'images/galbitang.jpg',
    price: '15,000원',
  },
  {
    shop: '김치찜',
    name: '장터김치찜 고양관산점',
    mainMenu: '삼겹 김치찜',
    img: 'images/kimchijjim.jpg',
    price: '23,900원',
  },
  {
    shop: '탕수육',
    name: '1키로탕수육 고양관산점',
    mainMenu: '1~2인용 탕수육',
    img: 'images/tangsuyuk.jpg',
    price: '14,900원',
  },
  {
    shop: '곱도리탕',
    name: '무대포주막촌',
    mainMenu: '1인 한우대창 곱도리탕',
    img: 'images/gopdoritang.jpg',
    price: '20,000원',
  },
  {
    shop: '육회비빔밥',
    name: '육회집',
    mainMenu: '한우 육회비빔밥',
    img: 'images/yukhoe.jpg',
    price: '13,000원',
  },
]

function recommendMenu() {
  const randomIndex = Math.floor(Math.random() * menus.length)
  const menu = menus[randomIndex]
  const card = document.getElementById('result-card')

  card.innerHTML = `
        <img src="${menu.img}" alt="${menu.name}">
        <h2>${menu.shop}</h2>
        <h3>${menu.name}</h3>
        <p>${menu.mainMenu}</p>
        <p>${menu.price}</p>
      `
  card.classList.remove('hidden')
  card.classList.add('show')
}
